# These are supported funding model platforms

github: kiramizuky
ko_fi: mastarom
buy_me_a_coffee: mastarom
paypal: https://paypal.me/AliMuhtarom
thanks_dev: gh/kiramizuky
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
